"""Shared layout and animation constants for TUI widgets."""

from __future__ import annotations

GRID_ROWS: tuple[tuple[str, str], ...] = (
    ("BACK_LEFT", "BACK_RIGHT"),
    ("FRONT_LEFT", "FRONT_RIGHT"),
)
CELL_WIDTH = 31
COMBAT_CELL_WIDTH = 14
COMBAT_FIELD_LAYOUT = "mini"
MINI_SLOT_WIDTH = 18
MINI_ART_WIDTH = 6
MINI_MIDDLE_WIDTH = 10
MINI_SIDE_GAP = "  "
MINI_VISIBLE_STATUS_TAGS = 2
PARTY_COMBAT_ROWS: tuple[tuple[str, str], ...] = (
    ("BACK_LEFT", "FRONT_LEFT"),
    ("BACK_RIGHT", "FRONT_RIGHT"),
)
ENEMY_COMBAT_ROWS: tuple[tuple[str, str], ...] = (
    ("FRONT_LEFT", "BACK_LEFT"),
    ("FRONT_RIGHT", "BACK_RIGHT"),
)
META_SEPARATOR = "  |  "
COMMAND_LABEL_WIDTH = 32
COMMAND_KEY_WIDTH = 6
DOCK_WIDE_MIN_WIDTH = 86
DOCK_COMMAND_COLUMN_WIDTH = 42
DOCK_GAP = "  |  "
MAP_NODE_WIDTH = 4
MAP_NODE_CENTER = (MAP_NODE_WIDTH - 1) // 2
MAP_X_STRIDE = 7
MAP_Y_STRIDE = 2
MAP_VIEWPORT_WIDTH = 31
MAP_VIEWPORT_HEIGHT = 9
FORMATION_INWARD_SLOTS = frozenset({"FRONT_LEFT", "FRONT_RIGHT"})
ACTION_ANIMATION_LAST_FRAME = 4
IDLE_ANIMATION_CYCLE = 4
ANTICIPATION_FRAME = 0
SOURCE_ACTION_FRAME = 1
DAMAGE_REACTION_FRAME = 3
PORTRAIT_EFFECT_LANE_COUNT = 2
BEAT_PORTRAIT_WIDTH = 32
BEAT_CONNECTOR_WIDTH = 8
BEAT_ART_SIDE_PADDING = 4
